name: Rubocop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@a699edbce608a2c128dedad88e3b6a0e28687b3c
        with:
          ruby-version: 2.6.6

      - name: Install gems
        run: |
          gem install rubocop -v 1.7.0
          gem install rubocop-minitest -v 0.11.0
          gem install rubocop-performance -v 1.10.1

      - name: Run Rubocop
        run: rubocop --except Metrics
